# Generated by Django 4.0.1 on 2022-01-29 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('primo_post', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussione',
                'verbose_name_plural': 'Discussioni',
            },
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=500)),
                ('immagine', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.discussione')),
                ('discussione_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_appartenenza', to='app.discussione')),
            ],
        ),
        migrations.AddField(
            model_name='discussione',
            name='sezione_appartenenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussioni_appartenenza', to='app.sezione'),
        ),
    ]
